// nodemailer.js
const nodemailer = require('nodemailer');

const SMTP_TRANSPORT = nodemailer.createTransport({
  host: process.env.SMTP_SERVICE,
  port: process.env.SMTP_PORT,
  secure: false,
  auth: {
    user: process.env.SMTP_USER, //generated by Mailtrap
    pass: process.env.SMTP_PASS, //generated by Mailtrap
  },
});

module.exports = { SMTP_TRANSPORT };
